/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Cartones.Carton;
import Control.ControladorBingo;
import ControladorBingo.controladorbingo;
import Excepciones.NumeroInvalidoException;
import Ganar.TipoJuego;
import Juego.ModoAutomatico;
import Juego.ModoJuego;
import Juego.ModoManual;
import Tablero.Tablero;
import java.awt.CardLayout;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nazar
 */
public class FrmVista extends javax.swing.JFrame {

    private controladorbingo control;
    private TipoJuego tipo;
    private ControladorBingo Controlador;

    /**
     * Creates new form FrmVista
     */
    public FrmVista() {
        initComponents();
        control = new controladorbingo();
        Mostrar1();
        Mostrar2();

        Controlador = new ControladorBingo((ModoJuego) cbModo.getSelectedItem());
//            hay errores aqui 
//        cbTipoJuego.setModel(new javax.swing.DefaultComboBoxModel<>(TipoJuego.values()));
        cbTipoJuego.setSelectedItem(TipoJuego.LINEA);
//        controlador = new ControladorBingo(new ModoManual()); // o ModoAutomatico
    }

    public void Mostrar1() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (TipoJuego tiposave : TipoJuego.values()) {
            model.addElement(tiposave);
        }
        cbTipoJuego.setModel(model);

    }

    public void Mostrar2() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (ModoJuego modosave : ModoJuego.values()) {
            model.addElement(modosave);
        }
        cbModo.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        Actual_JPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        txtNumeroManual = new javax.swing.JTextField();
        lblUltimoNumero = new javax.swing.JLabel();
        NumSalidos = new javax.swing.JButton();
        cbTipoJuego = new javax.swing.JComboBox<>();
        btnSiguienteAuto = new javax.swing.JButton();
        btnRegistrarManual = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        txtIdCarton = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cbModo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnCrearCartonAuto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Actual_JPanel.setLayout(null);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        Actual_JPanel.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 238, 248);

        txtNumeroManual.setText("Numero Manual");
        Actual_JPanel.add(txtNumeroManual);
        txtNumeroManual.setBounds(800, 150, 147, 26);

        lblUltimoNumero.setText("ultimo Numero");
        Actual_JPanel.add(lblUltimoNumero);
        lblUltimoNumero.setBounds(830, 90, 82, 16);

        NumSalidos.setText("Numeros Salidos");
        NumSalidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumSalidosActionPerformed(evt);
            }
        });
        Actual_JPanel.add(NumSalidos);
        NumSalidos.setBounds(800, 310, 147, 27);

        cbTipoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoJuegoActionPerformed(evt);
            }
        });
        Actual_JPanel.add(cbTipoJuego);
        cbTipoJuego.setBounds(700, 80, 122, 34);

        btnSiguienteAuto.setText("SiguienteNum (Auto)");
        btnSiguienteAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteAutoActionPerformed(evt);
            }
        });
        Actual_JPanel.add(btnSiguienteAuto);
        btnSiguienteAuto.setBounds(800, 190, 147, 27);

        btnRegistrarManual.setText("Registrar manual");
        Actual_JPanel.add(btnRegistrarManual);
        btnRegistrarManual.setBounds(800, 230, 147, 27);

        btnReiniciar.setText("Reiniciar Partida");
        Actual_JPanel.add(btnReiniciar);
        btnReiniciar.setBounds(800, 270, 147, 27);

        txtIdCarton.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##"))));
        txtIdCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCartonActionPerformed(evt);
            }
        });
        Actual_JPanel.add(txtIdCarton);
        txtIdCarton.setBounds(920, 80, 105, 34);

        jTextField1.setEditable(false);
        jTextField1.setText("IdCarton (0-99)");
        Actual_JPanel.add(jTextField1);
        jTextField1.setBounds(920, 40, 105, 26);

        jTextField2.setEditable(false);
        jTextField2.setText("Modo de juego");
        Actual_JPanel.add(jTextField2);
        jTextField2.setBounds(700, 40, 122, 26);

        Actual_JPanel.add(cbModo);
        cbModo.setBounds(570, 80, 102, 36);

        jMenu1.setText("Carton");

        btnCrearCartonAuto.setText("Nuevo Carton (Auto)");
        btnCrearCartonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCartonAutoActionPerformed(evt);
            }
        });
        jMenu1.add(btnCrearCartonAuto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actual_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1144, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Actual_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumSalidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumSalidosActionPerformed

        DlgNumSalidos NumSalidos = new DlgNumSalidos(this, true);
        NumSalidos.setVisible(true);
    }//GEN-LAST:event_NumSalidosActionPerformed

    private void cbTipoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoJuegoActionPerformed
        TipoJuego tipo = (TipoJuego) cbTipoJuego.getSelectedItem();
        control.setTipojuegoselec(tipo);

    }//GEN-LAST:event_cbTipoJuegoActionPerformed

    private void btnCrearCartonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCartonAutoActionPerformed
        String id = txtIdCarton.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID para el cartón");
            return;
        }
        try {
            Carton c = control.CrearCartonAutomatico(id);
            txtLog.append("Se creó el cartón automático con ID: " + id + "\n");

        } catch (NumeroInvalidoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        Bingo_InternalFrm CartonNew = new Bingo_InternalFrm();
        Actual_JPanel.add(CartonNew);
        CartonNew.setVisible(true);
        try {
            CartonNew.CrearCarton(control.CrearCartonAutomatico(id).getNumeros());
        } catch (NumeroInvalidoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearCartonAutoActionPerformed

    private void btnSiguienteAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteAutoActionPerformed
        int numero = control.siguienteNumeroAuto();

        if (numero == -1) {
            JOptionPane.showMessageDialog(this, "Ya no hay más números en la tómbola");
            return;
        }

        lblUltimoNumero.setText(String.valueOf(numero));
        txtLog.append("Salio el numero de manera automatica: " + numero);
        control.getServiciocarton().MarcarTodos(numero);
        // Verificar ganadores
        List<Carton> ganadores = control.obtenerGanadores();
        if (!ganadores.isEmpty()) {
            StringBuilder msg = new StringBuilder("¡Hay ganador(es)!\n");
            for (Carton c : ganadores) {
                msg.append("Cartón ID: ").append(c.getId()).append("\n");
            }
            JOptionPane.showMessageDialog(this, msg.toString(), "Bingo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnSiguienteAutoActionPerformed

    private void txtIdCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCartonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCartonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmVista().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actual_JPanel;
    private javax.swing.JButton NumSalidos;
    private javax.swing.JMenuItem btnCrearCartonAuto;
    private javax.swing.JButton btnRegistrarManual;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSiguienteAuto;
    private javax.swing.JComboBox<String> cbModo;
    private javax.swing.JComboBox<String> cbTipoJuego;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblUltimoNumero;
    private javax.swing.JFormattedTextField txtIdCarton;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtNumeroManual;
    // End of variables declaration//GEN-END:variables
}
